[2024-05-05T10:23:16.218+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-05T10:23:16.243+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_complex.delete_entry manual__2024-05-05T10:22:28.612296+00:00 [queued]>
[2024-05-05T10:23:16.250+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_complex.delete_entry manual__2024-05-05T10:22:28.612296+00:00 [queued]>
[2024-05-05T10:23:16.250+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-05T10:23:16.266+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): delete_entry> on 2024-05-05 10:22:28.612296+00:00
[2024-05-05T10:23:16.276+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2399) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-05T10:23:16.277+0000] {standard_task_runner.py:63} INFO - Started process 2401 to run task
[2024-05-05T10:23:16.276+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'example_complex', 'delete_entry', 'manual__2024-05-05T10:22:28.612296+00:00', '--job-id', '38', '--raw', '--subdir', '/home/***/.local/lib/python3.12/site-packages/***/example_dags/example_complex.py', '--cfg-path', '/tmp/tmp67k5wkea']
[2024-05-05T10:23:16.278+0000] {standard_task_runner.py:91} INFO - Job 38: Subtask delete_entry
[2024-05-05T10:23:16.316+0000] {task_command.py:426} INFO - Running <TaskInstance: example_complex.delete_entry manual__2024-05-05T10:22:28.612296+00:00 [running]> on host b2b5d11d7cf5
[2024-05-05T10:23:16.388+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_complex' AIRFLOW_CTX_TASK_ID='delete_entry' AIRFLOW_CTX_EXECUTION_DATE='2024-05-05T10:22:28.612296+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-05T10:22:28.612296+00:00'
[2024-05-05T10:23:16.391+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-05T10:23:16.392+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-05T10:23:16.393+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo delete_entry']
[2024-05-05T10:23:16.417+0000] {subprocess.py:86} INFO - Output:
[2024-05-05T10:23:16.420+0000] {subprocess.py:93} INFO - delete_entry
[2024-05-05T10:23:16.421+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-05T10:23:16.421+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-05T10:23:16.454+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=example_complex, task_id=delete_entry, execution_date=20240505T102228, start_date=20240505T102316, end_date=20240505T102316
[2024-05-05T10:23:16.495+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-05T10:23:16.517+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-05T10:23:16.524+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
